services:

    CoreShop\Payum\SaferpayBundle\Extension\ConvertPaymentExtension:
        autowire: true
        public: true
        tags:
            - { name: payum.extension, alias: saferpay_language_extension, factory: saferpay, gateway: saferpay, prepend: false }

    CoreShop\Payum\SaferpayBundle\Form\Payment\SaferpayType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: saferpay }
            - { name: form.type }

    CoreShop\Payum\SaferpayBundle\Event\RefundEvent:
        public: true
        arguments:
            - '@payum'

    payum.saferpay_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Karser\PayumSaferpay\SaferpayGatewayFactory]
        tags:
            - {name: payum.gateway_factory_builder, factory: saferpay }
